// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.Empty)
    com.google.protobuf.MessageOrBuilder {
}
