// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

public interface GetRankRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.GetRankRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
