// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

public interface InsertRankRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.InsertRankRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>int32 score = 2;</code>
   * @return The score.
   */
  int getScore();
}
