// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

/**
 * Protobuf type {@code com.example.rank.RankList}
 */
public final class RankList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.rank.RankList)
    RankListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RankList.newBuilder() to construct.
  private RankList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RankList() {
    ranks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RankList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RankList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ranks_ = new java.util.ArrayList<com.example.rank.RankInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            ranks_.add(
                input.readMessage(com.example.rank.RankInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ranks_ = java.util.Collections.unmodifiableList(ranks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.rank.Rank.internal_static_com_example_rank_RankList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.rank.Rank.internal_static_com_example_rank_RankList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.rank.RankList.class, com.example.rank.RankList.Builder.class);
  }

  public static final int RANKS_FIELD_NUMBER = 1;
  private java.util.List<com.example.rank.RankInfo> ranks_;
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.rank.RankInfo> getRanksList() {
    return ranks_;
  }
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.rank.RankInfoOrBuilder> 
      getRanksOrBuilderList() {
    return ranks_;
  }
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  @java.lang.Override
  public int getRanksCount() {
    return ranks_.size();
  }
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  @java.lang.Override
  public com.example.rank.RankInfo getRanks(int index) {
    return ranks_.get(index);
  }
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  @java.lang.Override
  public com.example.rank.RankInfoOrBuilder getRanksOrBuilder(
      int index) {
    return ranks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ranks_.size(); i++) {
      output.writeMessage(1, ranks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ranks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ranks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.rank.RankList)) {
      return super.equals(obj);
    }
    com.example.rank.RankList other = (com.example.rank.RankList) obj;

    if (!getRanksList()
        .equals(other.getRanksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRanksCount() > 0) {
      hash = (37 * hash) + RANKS_FIELD_NUMBER;
      hash = (53 * hash) + getRanksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.rank.RankList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.rank.RankList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.rank.RankList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.rank.RankList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.rank.RankList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.rank.RankList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.rank.RankList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.rank.RankList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.rank.RankList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.rank.RankList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.rank.RankList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.rank.RankList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.rank.RankList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.rank.RankList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.rank.RankList)
      com.example.rank.RankListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rank.Rank.internal_static_com_example_rank_RankList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rank.Rank.internal_static_com_example_rank_RankList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rank.RankList.class, com.example.rank.RankList.Builder.class);
    }

    // Construct using com.example.rank.RankList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRanksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ranksBuilder_ == null) {
        ranks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ranksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.rank.Rank.internal_static_com_example_rank_RankList_descriptor;
    }

    @java.lang.Override
    public com.example.rank.RankList getDefaultInstanceForType() {
      return com.example.rank.RankList.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.rank.RankList build() {
      com.example.rank.RankList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.rank.RankList buildPartial() {
      com.example.rank.RankList result = new com.example.rank.RankList(this);
      int from_bitField0_ = bitField0_;
      if (ranksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ranks_ = java.util.Collections.unmodifiableList(ranks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ranks_ = ranks_;
      } else {
        result.ranks_ = ranksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.rank.RankList) {
        return mergeFrom((com.example.rank.RankList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.rank.RankList other) {
      if (other == com.example.rank.RankList.getDefaultInstance()) return this;
      if (ranksBuilder_ == null) {
        if (!other.ranks_.isEmpty()) {
          if (ranks_.isEmpty()) {
            ranks_ = other.ranks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRanksIsMutable();
            ranks_.addAll(other.ranks_);
          }
          onChanged();
        }
      } else {
        if (!other.ranks_.isEmpty()) {
          if (ranksBuilder_.isEmpty()) {
            ranksBuilder_.dispose();
            ranksBuilder_ = null;
            ranks_ = other.ranks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ranksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRanksFieldBuilder() : null;
          } else {
            ranksBuilder_.addAllMessages(other.ranks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.rank.RankList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.rank.RankList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.rank.RankInfo> ranks_ =
      java.util.Collections.emptyList();
    private void ensureRanksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ranks_ = new java.util.ArrayList<com.example.rank.RankInfo>(ranks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.rank.RankInfo, com.example.rank.RankInfo.Builder, com.example.rank.RankInfoOrBuilder> ranksBuilder_;

    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public java.util.List<com.example.rank.RankInfo> getRanksList() {
      if (ranksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ranks_);
      } else {
        return ranksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public int getRanksCount() {
      if (ranksBuilder_ == null) {
        return ranks_.size();
      } else {
        return ranksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public com.example.rank.RankInfo getRanks(int index) {
      if (ranksBuilder_ == null) {
        return ranks_.get(index);
      } else {
        return ranksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder setRanks(
        int index, com.example.rank.RankInfo value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.set(index, value);
        onChanged();
      } else {
        ranksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder setRanks(
        int index, com.example.rank.RankInfo.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.set(index, builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder addRanks(com.example.rank.RankInfo value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.add(value);
        onChanged();
      } else {
        ranksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder addRanks(
        int index, com.example.rank.RankInfo value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.add(index, value);
        onChanged();
      } else {
        ranksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder addRanks(
        com.example.rank.RankInfo.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.add(builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder addRanks(
        int index, com.example.rank.RankInfo.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.add(index, builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder addAllRanks(
        java.lang.Iterable<? extends com.example.rank.RankInfo> values) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ranks_);
        onChanged();
      } else {
        ranksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder clearRanks() {
      if (ranksBuilder_ == null) {
        ranks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ranksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public Builder removeRanks(int index) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.remove(index);
        onChanged();
      } else {
        ranksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public com.example.rank.RankInfo.Builder getRanksBuilder(
        int index) {
      return getRanksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public com.example.rank.RankInfoOrBuilder getRanksOrBuilder(
        int index) {
      if (ranksBuilder_ == null) {
        return ranks_.get(index);  } else {
        return ranksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public java.util.List<? extends com.example.rank.RankInfoOrBuilder> 
         getRanksOrBuilderList() {
      if (ranksBuilder_ != null) {
        return ranksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ranks_);
      }
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public com.example.rank.RankInfo.Builder addRanksBuilder() {
      return getRanksFieldBuilder().addBuilder(
          com.example.rank.RankInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public com.example.rank.RankInfo.Builder addRanksBuilder(
        int index) {
      return getRanksFieldBuilder().addBuilder(
          index, com.example.rank.RankInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
     */
    public java.util.List<com.example.rank.RankInfo.Builder> 
         getRanksBuilderList() {
      return getRanksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.rank.RankInfo, com.example.rank.RankInfo.Builder, com.example.rank.RankInfoOrBuilder> 
        getRanksFieldBuilder() {
      if (ranksBuilder_ == null) {
        ranksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.rank.RankInfo, com.example.rank.RankInfo.Builder, com.example.rank.RankInfoOrBuilder>(
                ranks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ranks_ = null;
      }
      return ranksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.rank.RankList)
  }

  // @@protoc_insertion_point(class_scope:com.example.rank.RankList)
  private static final com.example.rank.RankList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.rank.RankList();
  }

  public static com.example.rank.RankList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RankList>
      PARSER = new com.google.protobuf.AbstractParser<RankList>() {
    @java.lang.Override
    public RankList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RankList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RankList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RankList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.rank.RankList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

