// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

public interface RankListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.RankList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  java.util.List<com.example.rank.RankInfo> 
      getRanksList();
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  com.example.rank.RankInfo getRanks(int index);
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  int getRanksCount();
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  java.util.List<? extends com.example.rank.RankInfoOrBuilder> 
      getRanksOrBuilderList();
  /**
   * <code>repeated .com.example.rank.RankInfo ranks = 1;</code>
   */
  com.example.rank.RankInfoOrBuilder getRanksOrBuilder(
      int index);
}
