// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.example.rank;

public final class Rank {
  private Rank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_rank_RankInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_rank_RankInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_rank_InsertRankRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_rank_InsertRankRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_rank_GetRankRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_rank_GetRankRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_rank_RankList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_rank_RankList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_rank_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_rank_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrank.proto\022\020com.example.rank\"&\n\010RankIn" +
      "fo\022\014\n\004name\030\001 \001(\t\022\014\n\004uuid\030\002 \001(\t\"0\n\021Insert" +
      "RankRequest\022\014\n\004uuid\030\001 \001(\t\022\r\n\005score\030\002 \001(\005" +
      "\"\036\n\016GetRankRequest\022\014\n\004uuid\030\001 \001(\t\"5\n\010Rank" +
      "List\022)\n\005ranks\030\001 \003(\0132\032.com.example.rank.R" +
      "ankInfo\"\007\n\005Empty2\361\002\n\013RankService\022@\n\007addR" +
      "ank\022\032.com.example.rank.RankInfo\032\027.com.ex" +
      "ample.rank.Empty\"\000\022L\n\ninsertRank\022#.com.e" +
      "xample.rank.InsertRankRequest\032\027.com.exam" +
      "ple.rank.Empty\"\000\022I\n\007getRank\022 .com.exampl" +
      "e.rank.GetRankRequest\032\032.com.example.rank" +
      ".RankInfo\"\000\022C\n\ngetAllRank\022\027.com.example." +
      "rank.Empty\032\032.com.example.rank.RankList\"\000" +
      "\022B\n\tclearRank\022\032.com.example.rank.RankInf" +
      "o\032\027.com.example.rank.Empty\"\000B\024\n\020com.exam" +
      "ple.rankP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_rank_RankInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_rank_RankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_rank_RankInfo_descriptor,
        new java.lang.String[] { "Name", "Uuid", });
    internal_static_com_example_rank_InsertRankRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_rank_InsertRankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_rank_InsertRankRequest_descriptor,
        new java.lang.String[] { "Uuid", "Score", });
    internal_static_com_example_rank_GetRankRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_rank_GetRankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_rank_GetRankRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_com_example_rank_RankList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_rank_RankList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_rank_RankList_descriptor,
        new java.lang.String[] { "Ranks", });
    internal_static_com_example_rank_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_rank_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_rank_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
