// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface CreateRankResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.CreateRankResponse)
    com.google.protobuf.MessageOrBuilder {
}
