// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface CreateRankRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.CreateRankRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string uuid = 2;</code>
   */
  String getUuid();
  /**
   * <code>string uuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
