// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface GetAllRanksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.GetAllRanksRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rankName = 1;</code>
   */
  String getRankName();
  /**
   * <code>string rankName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRankNameBytes();
}
