// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface GetAllRanksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.GetAllRanksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  java.util.List<Rank>
      getRanksList();
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  Rank getRanks(int index);
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  int getRanksCount();
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  java.util.List<? extends RankOrBuilder>
      getRanksOrBuilderList();
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  RankOrBuilder getRanksOrBuilder(
      int index);
}
