// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

/**
 * Protobuf type {@code com.example.rank.GetAllRanksResponse}
 */
public  final class GetAllRanksResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.rank.GetAllRanksResponse)
        GetAllRanksResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllRanksResponse.newBuilder() to construct.
  private GetAllRanksResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllRanksResponse() {
    ranks_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllRanksResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ranks_ = new java.util.ArrayList<Rank>();
              mutable_bitField0_ |= 0x00000001;
            }
            ranks_.add(
                input.readMessage(Rank.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ranks_ = java.util.Collections.unmodifiableList(ranks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RankProto.internal_static_com_example_rank_GetAllRanksResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RankProto.internal_static_com_example_rank_GetAllRanksResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetAllRanksResponse.class, GetAllRanksResponse.Builder.class);
  }

  public static final int RANKS_FIELD_NUMBER = 1;
  private java.util.List<Rank> ranks_;
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  public java.util.List<Rank> getRanksList() {
    return ranks_;
  }
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  public java.util.List<? extends RankOrBuilder>
      getRanksOrBuilderList() {
    return ranks_;
  }
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  public int getRanksCount() {
    return ranks_.size();
  }
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  public Rank getRanks(int index) {
    return ranks_.get(index);
  }
  /**
   * <code>repeated .com.example.rank.Rank ranks = 1;</code>
   */
  public RankOrBuilder getRanksOrBuilder(
      int index) {
    return ranks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ranks_.size(); i++) {
      output.writeMessage(1, ranks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ranks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ranks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetAllRanksResponse)) {
      return super.equals(obj);
    }
    GetAllRanksResponse other = (GetAllRanksResponse) obj;

    boolean result = true;
    result = result && getRanksList()
        .equals(other.getRanksList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRanksCount() > 0) {
      hash = (37 * hash) + RANKS_FIELD_NUMBER;
      hash = (53 * hash) + getRanksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetAllRanksResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllRanksResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllRanksResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllRanksResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllRanksResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllRanksResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllRanksResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetAllRanksResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetAllRanksResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetAllRanksResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetAllRanksResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetAllRanksResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetAllRanksResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.rank.GetAllRanksResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.rank.GetAllRanksResponse)
          GetAllRanksResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RankProto.internal_static_com_example_rank_GetAllRanksResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RankProto.internal_static_com_example_rank_GetAllRanksResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetAllRanksResponse.class, GetAllRanksResponse.Builder.class);
    }

    // Construct using com.example.rank.GetAllRanksResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRanksFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (ranksBuilder_ == null) {
        ranks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ranksBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RankProto.internal_static_com_example_rank_GetAllRanksResponse_descriptor;
    }

    public GetAllRanksResponse getDefaultInstanceForType() {
      return GetAllRanksResponse.getDefaultInstance();
    }

    public GetAllRanksResponse build() {
      GetAllRanksResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public GetAllRanksResponse buildPartial() {
      GetAllRanksResponse result = new GetAllRanksResponse(this);
      int from_bitField0_ = bitField0_;
      if (ranksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ranks_ = java.util.Collections.unmodifiableList(ranks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ranks_ = ranks_;
      } else {
        result.ranks_ = ranksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetAllRanksResponse) {
        return mergeFrom((GetAllRanksResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetAllRanksResponse other) {
      if (other == GetAllRanksResponse.getDefaultInstance()) return this;
      if (ranksBuilder_ == null) {
        if (!other.ranks_.isEmpty()) {
          if (ranks_.isEmpty()) {
            ranks_ = other.ranks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRanksIsMutable();
            ranks_.addAll(other.ranks_);
          }
          onChanged();
        }
      } else {
        if (!other.ranks_.isEmpty()) {
          if (ranksBuilder_.isEmpty()) {
            ranksBuilder_.dispose();
            ranksBuilder_ = null;
            ranks_ = other.ranks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ranksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRanksFieldBuilder() : null;
          } else {
            ranksBuilder_.addAllMessages(other.ranks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GetAllRanksResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GetAllRanksResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Rank> ranks_ =
      java.util.Collections.emptyList();
    private void ensureRanksIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ranks_ = new java.util.ArrayList<Rank>(ranks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Rank, Rank.Builder, RankOrBuilder> ranksBuilder_;

    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public java.util.List<Rank> getRanksList() {
      if (ranksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ranks_);
      } else {
        return ranksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public int getRanksCount() {
      if (ranksBuilder_ == null) {
        return ranks_.size();
      } else {
        return ranksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Rank getRanks(int index) {
      if (ranksBuilder_ == null) {
        return ranks_.get(index);
      } else {
        return ranksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder setRanks(
        int index, Rank value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.set(index, value);
        onChanged();
      } else {
        ranksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder setRanks(
        int index, Rank.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.set(index, builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder addRanks(Rank value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.add(value);
        onChanged();
      } else {
        ranksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder addRanks(
        int index, Rank value) {
      if (ranksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRanksIsMutable();
        ranks_.add(index, value);
        onChanged();
      } else {
        ranksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder addRanks(
        Rank.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.add(builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder addRanks(
        int index, Rank.Builder builderForValue) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.add(index, builderForValue.build());
        onChanged();
      } else {
        ranksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder addAllRanks(
        Iterable<? extends Rank> values) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ranks_);
        onChanged();
      } else {
        ranksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder clearRanks() {
      if (ranksBuilder_ == null) {
        ranks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ranksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Builder removeRanks(int index) {
      if (ranksBuilder_ == null) {
        ensureRanksIsMutable();
        ranks_.remove(index);
        onChanged();
      } else {
        ranksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Rank.Builder getRanksBuilder(
        int index) {
      return getRanksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public RankOrBuilder getRanksOrBuilder(
        int index) {
      if (ranksBuilder_ == null) {
        return ranks_.get(index);  } else {
        return ranksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public java.util.List<? extends RankOrBuilder>
         getRanksOrBuilderList() {
      if (ranksBuilder_ != null) {
        return ranksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ranks_);
      }
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Rank.Builder addRanksBuilder() {
      return getRanksFieldBuilder().addBuilder(
          Rank.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public Rank.Builder addRanksBuilder(
        int index) {
      return getRanksFieldBuilder().addBuilder(
          index, Rank.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.rank.Rank ranks = 1;</code>
     */
    public java.util.List<Rank.Builder>
         getRanksBuilderList() {
      return getRanksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Rank, Rank.Builder, RankOrBuilder>
        getRanksFieldBuilder() {
      if (ranksBuilder_ == null) {
        ranksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Rank, Rank.Builder, RankOrBuilder>(
                ranks_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        ranks_ = null;
      }
      return ranksBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.rank.GetAllRanksResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.rank.GetAllRanksResponse)
  private static final GetAllRanksResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetAllRanksResponse();
  }

  public static GetAllRanksResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllRanksResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllRanksResponse>() {
    public GetAllRanksResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllRanksResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllRanksResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetAllRanksResponse> getParserForType() {
    return PARSER;
  }

  public GetAllRanksResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

