// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface GetRankByUuidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.GetRankByUuidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string rankName = 2;</code>
   */
  String getRankName();
  /**
   * <code>string rankName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRankNameBytes();
}
