// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package rank.rank;

public interface GetRankByUuidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.rank.GetRankByUuidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rank = 1;</code>
   */
  int getRank();
}
